"""empty message

Revision ID: 2152a7d8428d
Revises: 4f1b6b7796c6
Create Date: 2022-12-14 18:14:19.903717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2152a7d8428d'
down_revision = '4f1b6b7796c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictogramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hijos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('dia_semana', sa.String(length=80), nullable=False),
    sa.Column('momento_dia', sa.String(length=80), nullable=False),
    sa.Column('pictogramas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pictogramas_id'], ['pictogramas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=80), nullable=True),
    sa.Column('is_parents', sa.Boolean(), nullable=False),
    sa.Column('hijos_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hijos_id'], ['hijos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('hijos')
    op.drop_table('pictogramas')
    # ### end Alembic commands ###
