"""empty message

Revision ID: 4f1b6b7796c6
Revises: 3b76045ac536
Create Date: 2022-12-12 16:33:10.276001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1b6b7796c6'
down_revision = '3b76045ac536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('is_parents', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['apellidos'])
        batch_op.create_unique_constraint(None, ['telefono'])
        batch_op.create_unique_constraint(None, ['direccion'])
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_parents')
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
