"""empty message

Revision ID: 556475ca5f4e
Revises: 7eea92f84832
Create Date: 2022-12-27 19:08:23.461874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556475ca5f4e'
down_revision = '7eea92f84832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relacion')
    op.drop_table('hijos')
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('apellidos', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_column('apellidos')
        batch_op.drop_column('nombre')

    op.create_table('hijos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('hijos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('agenda_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agenda.id'], name='hijos_agenda_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hijos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('relacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hijos_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hijos_id'], ['hijos.id'], name='relacion_hijos_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='relacion_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='relacion_pkey')
    )
    # ### end Alembic commands ###
