"""empty message

Revision ID: b83d2451f4c4
Revises: 6b32c49a5f6b
Create Date: 2022-12-20 16:49:05.562978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83d2451f4c4'
down_revision = '6b32c49a5f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hijos_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hijos_id'], ['hijos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_hijos_id_fkey', type_='foreignkey')
        batch_op.drop_column('hijos_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hijos_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_hijos_id_fkey', 'hijos', ['hijos_id'], ['id'])

    op.drop_table('relacion')
    # ### end Alembic commands ###
