"""empty message

Revision ID: e531c81fdb0d
Revises: 90a16111b97a
Create Date: 2023-01-11 10:35:43.920572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e531c81fdb0d'
down_revision = '90a16111b97a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urlP', sa.String(length=200), nullable=False))
        batch_op.drop_constraint('agenda_pictogramas_id_fkey', type_='foreignkey')
        batch_op.drop_column('pictogramas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pictogramas_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('agenda_pictogramas_id_fkey', 'pictogramas', ['pictogramas_id'], ['id'])
        batch_op.drop_column('urlP')

    # ### end Alembic commands ###
