"""empty message

Revision ID: fbc532f30be9
Revises: 55eb84129fe7
Create Date: 2022-12-14 20:19:59.203364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc532f30be9'
down_revision = '55eb84129fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictograma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=250), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dias_semana', sa.String(length=30), nullable=False),
    sa.Column('momentos_del_dia', sa.String(length=30), nullable=False),
    sa.Column('pictograma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pictograma_id'], ['pictograma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pictogramas')
    with op.batch_alter_table('hijos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agenda_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('hijos_pictogramas_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'agenda', ['agenda_id'], ['id'])
        batch_op.drop_column('momento_dia')
        batch_op.drop_column('dia_semana')
        batch_op.drop_column('pictogramas_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hijos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pictogramas_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dia_semana', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('momento_dia', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hijos_pictogramas_id_fkey', 'pictogramas', ['pictogramas_id'], ['id'])
        batch_op.drop_column('agenda_id')

    op.create_table('pictogramas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pictogramas_pkey')
    )
    op.drop_table('agenda')
    op.drop_table('pictograma')
    # ### end Alembic commands ###
